variables:
  - &node_image "node:16-alpine"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64,linux/arm64"

pipeline:
  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/aqurilla
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/aqurilla
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

branches: [main]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
